[package]
name = "rhizome-pith-websocket-wasm"
description = "WASM implementation of pith-websocket"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-pith-websocket = { path = "../../../interfaces/pith-websocket" }
gloo-net = { version = "0.6", features = ["websocket"] }
futures = "0.3"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
