[package]
name = "portals-encoding-portable"
description = "Portable implementation of portals-encoding (works on native and WASM)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
portals-encoding = { path = "../../../interfaces/portals-encoding" }
base64 = "0.22"
