[package]
name = "rhizome-pith-random-native"
description = "Native implementation of pith-random"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-random = { path = "../../../interfaces/pith-random" }
getrandom.workspace = true
