[package]
name = "portals-snowflake-native"
description = "Native snowflake ID implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
portals-snowflake = { path = "../../../interfaces/portals-snowflake" }
