[package]
name = "portals-websocket-wasm"
description = "WASM implementation of portals-websocket"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
portals-websocket = { path = "../../../interfaces/portals-websocket" }
gloo-net = { version = "0.6", features = ["websocket"] }
futures = "0.3"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
