[package]
name = "rhizome-pith-observe-native"
description = "Native observability implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-observe = { path = "../../../interfaces/pith-observe" }
