[package]
name = "rhizome-pith-filesystem"
description = "Filesystem interfaces"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-io = { path = "../pith-io" }
