[package]
name = "rhizome-pith-snowflake-native"
description = "Native snowflake ID implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-pith-snowflake = { path = "../../../interfaces/pith-snowflake" }
