[package]
name = "rhizome-pith-config-native"
description = "Native configuration implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-config = { path = "../../../interfaces/pith-config" }
