[package]
name = "portals-random-mock"
description = "Mock implementation of portals-random for testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
portals-random = { path = "../../../interfaces/portals-random" }
