[package]
name = "rhizome-pith-nanoid-native"
description = "Native nanoid implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-nanoid = { path = "../../../interfaces/pith-nanoid" }
nanoid = "0.4"
