[package]
name = "rhizome-pith-cache-native"
description = "Native in-memory cache implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-cache = { path = "../../../interfaces/pith-cache" }
