[package]
name = "rhizome-pith-random-wasm"
description = "WASM implementation of pith-random"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-rhi-portals-random = { path = "../../../interfaces/pith-random" }
getrandom = { version = "0.3", features = ["wasm_js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
